- name: Deploy Vault to secret hosts
  hosts: vault
  gather_facts: no
  become: yes # Sudo as root

  tasks:

    - name: Create vault user
      ansible.builtin.user:
        name: vault
        shell: /bin/false # Don't allow login

    - name: Install gpg
      ansible.builtin.apt:
        name: gpg

    - name: Add the HashiCorp GPG key
      ansible.builtin.shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg \
        | gpg --dearmor \
        | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add the official HashiCorp Linux repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
        | sudo tee /etc/apt/sources.list.d/hashicorp.list
      args:
        creates: /etc/apt/sources.list.d/hashicorp.list

    - name: Install vault
      ansible.builtin.apt:
        name: vault
        update_cache: yes

    - name: Checkout repository
      become: yes
      become_user: vault
      ansible.builtin.git:
        repo: "https://{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}@github.com/IFS4205-TraceIT/vault-management"
        dest: /home/vault/repo

    - name: Copy configuration file
      become: yes
      become_user: vault
      ansible.builtin.copy:
        src: /home/vault/repo/vault.hcl
        dest: /etc/vault.d/vault.hcl
        remote_src: yes

    - name: Start vault service
      ansible.builtin.systemd:
        name: vault
        enabled: yes
        state: started

    - name: Initialize vault
      become: yes
      become_user: vault
      ansible.builtin.command:
        argv:
          - vault
          - operator
          - init
          - "-key-shares={{ lookup('ansible.builtin.env', 'KEY_SHARES') }}"
          - "-key-threshold={{ lookup('ansible.builtin.env', 'KEY_THRESHOLD') }}"
      environment:
        VAULT_SKIP_VERIFY: true
      register: vault_output

    - name: Print unseal key(s) and initial root token
      debug: 
        msg:
          - "{{ vault_output.stdout_lines }}"