- name: Deploy NGINX to proxy hosts
  hosts: nginx
  gather_facts: no
  become: yes # Sudo as root

  tasks:

    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Create /tracer web directory
      ansible.builtin.file:
        state: directory
        path: /var/www/tracer
        owner: root
        group: root
        mode: 0755

    - name: Create /research web directory
      ansible.builtin.file:
        state: directory
        path: /var/www/research
        owner: root
        group: root
        mode: 0755

    - name: Unarchive tracer-frontend files
      ansible.builtin.unarchive:
        src: tracer-frontend.tar.gz
        dest: /var/www/tracer

    - name: Apply config
      ansible.builtin.copy:
        mode: 0644
        dest: /etc/nginx/sites-available/default
        content: |
          server { 
            listen       80;

            location /tracer/api {
              proxy_pass      http://traceit-01-i.comp.nus.edu.sg:8000;
            }

            location /research/api {
              proxy_pass      http://traceit-02-i.comp.nus.edu.sg:8000;
            }

            location /tracer {  
              alias       /var/www/tracer;
              try_files $uri $uri/ $uri.html /index.html;
            }
            location /research {  
              alias       /var/www/research;
              try_files $uri $uri/ $uri.html /index.html;
            }
          }

    - name: Reload NGINX
      ansible.builtin.systemd:
        name: nginx.service
        state: reloaded