- name: Deploy NGINX to proxy hosts
  hosts: nginx
  gather_facts: no
  become: yes # Sudo as root

  tasks:

    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Request new server certificate
      community.hashi_vault.vault_write:
        url: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
        path: pki_int/issue/traceit-04-i.comp.nus.edu.sg
        auth_method: token
        token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN') }}"
        validate_certs: yes
        token_validate: false
        data:
          common_name: traceit-04-i.comp.nus.edu.sg
          ttl: 767h
      register: server_certificate_output

    - name: Add server certificate
      ansible.builtin.copy:
        dest: /etc/nginx/server.crt
        owner: root
        group: root
        mode: 0400
        content: "{{ server_certificate_output.data.data.certificate }}"

    - name: Add server private key
      ansible.builtin.copy:
        dest: /etc/nginx/server.key
        owner: root
        group: root
        mode: 0400
        content: "{{ server_certificate_output.data.data.private_key }}"

    - name: Create /tracer web directory
      ansible.builtin.file:
        state: directory
        path: /var/www/tracer
        owner: root
        group: root
        mode: 0755

    - name: Create /research web directory
      ansible.builtin.file:
        state: directory
        path: /var/www/research
        owner: root
        group: root
        mode: 0755

    - name: Unarchive tracer-frontend files
      ansible.builtin.unarchive:
        src: tracer-frontend.tar.gz
        dest: /var/www/tracer

    - name: Unarchive research-frontend files
      ansible.builtin.unarchive:
        src: research-frontend.tar.gz
        dest: /var/www/research

    - name: Apply config
      ansible.builtin.copy:
        mode: 0644
        dest: /etc/nginx/sites-available/default
        content: |
          server { 
            listen       80;
            # listen       443 ssl;
            # ssl_certificate     /etc/nginx/server.crt;
            # ssl_certificate_key /etc/nginx/server.key;

            location /tracer/api {
              rewrite ^/tracer/api(.*) $1 break;
              proxy_set_header Host traceit-04-i.comp.nus.edu.sg;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass      https://traceit-01-i.comp.nus.edu.sg:8000;
              proxy_ssl_trusted_certificate /usr/local/share/ca-certificates/traceit-ca.crt;
              proxy_ssl_verify       on;
              proxy_ssl_session_reuse on;
              proxy_ssl_verify_depth  2;
              proxy_ssl_certificate     /etc/nginx/server.crt;
              proxy_ssl_certificate_key /etc/nginx/server.key;
            }

            location /research/api {
              rewrite ^/research/api(.*) $1 break;
              proxy_set_header Host traceit-04-i.comp.nus.edu.sg;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass      https://traceit-02-i.comp.nus.edu.sg:8000;
              proxy_ssl_trusted_certificate /usr/local/share/ca-certificates/traceit-ca.crt;
              proxy_ssl_verify       on;
              proxy_ssl_session_reuse on;
              proxy_ssl_verify_depth  2;
              proxy_ssl_certificate     /etc/nginx/server.crt;
              proxy_ssl_certificate_key /etc/nginx/server.key;
            }

            location /contact/api {
              rewrite ^/contact/api(.*) $1 break;
              proxy_set_header Host traceit-04-i.comp.nus.edu.sg;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass      https://traceit-03-i.comp.nus.edu.sg:8000;
              proxy_ssl_trusted_certificate /usr/local/share/ca-certificates/traceit-ca.crt;
              proxy_ssl_verify       on;
              proxy_ssl_session_reuse on;
              proxy_ssl_verify_depth  2;
              proxy_ssl_certificate     /etc/nginx/server.crt;
              proxy_ssl_certificate_key /etc/nginx/server.key;
            }

            location /tracer {  
              alias       /var/www/tracer;
              try_files $uri $uri/ $uri.html /index.html;
            }
            location /research {  
              alias       /var/www/research;
              try_files $uri $uri/ $uri.html /index.html;
            }
          }

    - name: Reload NGINX
      ansible.builtin.systemd:
        name: nginx.service
        state: reloaded