- name: Deploy PostgreSQL TDE to database hosts
  hosts: "{{ db_hosts }}"
  gather_facts: no
  become: yes # Sudo as root

  tasks:

    - name: Create postgres user
      ansible.builtin.user:
        name: postgres
        shell: /bin/false # Don't allow login

    - name: Download artifact
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: /home/postgres/postgresql_tde.tar.gz
        owner: postgres
        group: postgres
        checksum: "sha256:{{ download_sha256 }}"
        mode: 0400
        headers:
          Authorization: "token {{ git_pat }}"
          Accept: "application/octet-stream"

    - name: Extract files to home directory
      ansible.builtin.unarchive:
        remote_src: yes
        src: /home/postgres/postgresql_tde.tar.gz
        dest: /home/postgres/
        owner: postgres
        group: postgres

    - name: Create POC key manager file in home directory
      ansible.builtin.copy:
        dest: /home/postgres/key_manager.sh
        owner: postgres
        group: postgres
        mode: 0500
        content: |
          #!/bin/bash
          echo "${ENCRYPTION_KEY}"

    - name: Create database folder
      ansible.builtin.file:
        path: /opt/postgresql_db/
        state: directory
        owner: postgres
        group: postgres

    - name: Initialize database cluster
      become: yes
      become_user: postgres
      args:
        chdir: /home/postgres/postgresql_tde/bin
      ansible.builtin.command:
        argv:
          - ./initdb
          - -D
          - /opt/postgresql_db/
          - -K
          - /home/postgres/key_manager.sh
        creates: /opt/postgresql_db/PG_VERSION # Used to track if cluster is already created
      environment:
        LD_LIBRARY_PATH: /home/postgres/postgresql_tde/lib
        ENCRYPTION_KEY: "{{ encryption_key }}"

    - name: Create database log
      ansible.builtin.file:
        path: /var/log/postgresql_tde.log
        state: touch
        owner: postgres
        group: postgres
        mode: 0600

    - name: Check if database service is already listening
      wait_for:
        port: 5432
        delay: 5
        timeout: 10
      register: port_check
      ignore_errors: yes

    - name: Start database service
      when: port_check.failed
      become: yes
      become_user: postgres
      args:
        chdir: /home/postgres/postgresql_tde/bin
      ansible.builtin.command:
        argv:
          - ./pg_ctl
          - -D
          - /opt/postgresql_db/
          - -l
          - /var/log/postgresql_tde.log
          - start
      environment:
        LD_LIBRARY_PATH: /home/postgres/postgresql_tde/lib
        ENCRYPTION_KEY: "{{ encryption_key }}"
