- name: Mount secret engines
  hosts: vault
  gather_facts: no
  become: yes
  become_user: vault

  environment:
    VAULT_TOKEN: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN') }}"
    VAULT_ADDR: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"

  tasks:

    - name: Enable TOTP Secrets Engine
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - totp
      ignore_errors: yes

    - name: Enable Database Secrets Engine
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - database
      ignore_errors: yes
    
    - name: Enable KV Secrets Engine
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - kv
      ignore_errors: yes

    - name: Enable KV V2 Secrets Engine
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - kv-v2
      ignore_errors: yes
    
    - name: Enable PKI Secrets Engine for Root CA
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - pki
      ignore_errors: yes

    - name: Enable PKI Secrets Engine for Intermediate CA
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - -path=pki_int
          - pki
      ignore_errors: yes
