- name: Setup hosts
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Add SSH authorized key
      ansible.posix.authorized_key:
        user: sadm
        state: present
        key: "{{ lookup('file', lookup('ansible.builtin.env','HOME') + '/.ssh/id_ed25519.pub') }}"
    
    - name: Configure passwordless sudo
      community.general.sudoers:
        name: passwordless-sudo
        state: present
        user: sadm
        runas: ALL
        commands: ALL
        nopassword: true

    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install acl
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install hvac python package
      ansible.builtin.pip:
        name: hvac
