- name: Teardown NGINX from proxy hosts
  hosts: nginx
  gather_facts: no
  become: yes # Sudo as root

  tasks:

    - name: Stop NGINX
      ansible.builtin.systemd:
        name: nginx.service
        state: stopped

    - name: Remove /tracer web directory
      ansible.builtin.file:
        state: absent
        path: /var/www/tracer

    - name: Remove /research web directory
      ansible.builtin.file:
        state: absent
        path: /var/www/research

    - name: Remove cert
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /etc/nginx/server.key
        - /etc/nginx/server.crt
