- name: Teardown Django + Gunicorn from app servers
  hosts: "{{ lookup('ansible.builtin.env', 'APP_HOSTS') }}"
  gather_facts: no
  become: yes # Sudo as root

  tasks:
    - name: Stop gunicorn
      become: yes
      become_user: django
      args:
        chdir: /home/django/repo
      ansible.builtin.shell: |
        kill $(cat *.pid)
      ignore_errors: yes
    
    - name: Delete virtual environment
      become: yes
      become_user: django
      args:
        chdir: /home/django/repo
      ansible.builtin.shell: |
        export PATH=/home/django/.local/bin:$PATH
        poetry env remove python3.10
      ignore_errors: yes

    - name: Delete repository
      become: yes
      become_user: django
      ansible.builtin.file:
        path: /home/django/repo
        state: absent

    - name: Remove gunicorn access log
      ansible.builtin.file:
        path: /var/log/gunicorn_access.log
        state: absent
    
    - name: Remove gunicorn error log
      ansible.builtin.file:
        path: /var/log/gunicorn_error.log
        state: absent