- name: Unseal Vault
  hosts: vault
  gather_facts: no
  become: yes
  become_user: vault

  environment:
    VAULT_ADDR: "https://traceit-07-i.comp.nus.edu.sg:8200"
    VAULT_CACERT: "/home/vault/ca.crt"

  tasks:

    - name: Unseal vault
      ansible.builtin.uri:
        method: POST
        url: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}/v1/sys/unseal"
        body:
          key: "{{ lookup('ansible.builtin.env', 'UNSEAL_KEY') }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        validate_certs: yes
        ca_path: /home/vault/ca.crt

