- name: Unseal Vault on secret hosts
  hosts: vault
  gather_facts: no

  environment:
    VAULT_SKIP_VERIFY: true

  tasks:

    - name: Unseal vault
      ansible.builtin.uri:
        url: https://127.0.0.1:8200/v1/sys/unseal
        method: POST
        body:
          key: "{{ lookup('ansible.builtin.env', 'UNSEAL_KEY') }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        validate_certs: no
