- name: Unseal Vault on secret hosts
  hosts: vault
  gather_facts: no

  environment:
    VAULT_SKIP_VERIFY: true
    VAULT_TOKEN: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN') }}"

  tasks:

    - name: Unseal vault
      ansible.builtin.uri:
        url: https://127.0.0.1:8200/v1/sys/unseal
        method: POST
        body:
          key: "{{ lookup('ansible.builtin.env', 'UNSEAL_KEY') }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        validate_certs: no

    - name: Enable TOTP Secrets Engine
      become: yes
      become_user: vault
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - totp
      ignore_errors: yes

    - name: Enable Database Secrets Engine
      become: yes
      become_user: vault
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - database
      ignore_errors: yes
    
    - name: KV Secrets Engine
      become: yes
      become_user: vault
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - kv
      ignore_errors: yes

    - name: KV V2 Secrets Engine
      become: yes
      become_user: vault
      ansible.builtin.command:
        argv:
          - vault
          - secrets
          - enable
          - kv-v2
      ignore_errors: yes
