name: Deploy
on:
  workflow_dispatch:

jobs:
  
  deploy:

    runs-on: cd-test
    container: ubuntu:20.04

    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      
      - name: Install ansible and dependencies
        run: |
          apt-get update
          apt-get install -y software-properties-common
          apt-add-repository -y ppa:ansible/ansible
          apt-get update
          apt-get install -y sshpass ansible ansible-lint

      - name: Check installation
        run: |
          ansible --version