name: Deploy
on:
  workflow_dispatch:

jobs:
  
  deploy:

    runs-on: cd-test
    container: 
      image: willhallonline/ansible:2.12-ubuntu-20.04
      options: --dns 192.168.1.101

    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Check installation
        run: |
          ansible --version

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate database secrets for Database 1
        env:
          DATABASE_NAME: database1
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/write_database_keys.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml

      - name: Get Database 1 secrets from Vault
        uses: hashicorp/vault-action@v2.4.0
        id: database1-secrets
        with:
          url: https://traceit-07-i.comp.nus.edu.sg:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
              kv/database1 tde_key | TDE_KEY;
              kv/database1 root_password | POSTGRES_ROOT_PASSWORD;
          exportEnv: false

      - name: Download PostgreSQL TDE release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: IFS4205-TraceIT/PostgreSQL-TDE
          version: tags/vlatest
          file: postgresql_tde.tar.gz 
          token: ${{ secrets.PAT }}
          target: playbooks/files/postgresql_tde.tar.gz

      - name: Deploy Database 1
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DB_HOSTS: traceit-01-i.comp.nus.edu.sg
          TDE_KEY:                "${{ steps.database1-secrets.outputs.TDE_KEY }}"
          POSTGRES_ROOT_PASSWORD: "${{ steps.database1-secrets.outputs.POSTGRES_ROOT_PASSWORD }}"
          VAULT_TOKEN:            "${{ secrets.VAULT_TOKEN }}"
        with:
          playbook: playbooks/deploy_postgres.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml

      - name: Generate django secrets for tracer_backend
        env:
          APP_NAME: tracer_backend
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/write_django_keys.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml

      - name: Generate django secrets for research_backend
        env:
          APP_NAME: research_backend
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/write_django_keys.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml      

      - name: Get tracer_backend secrets from Vault
        uses: hashicorp/vault-action@v2.4.0
        id: tracer_backend-secrets
        with:
          url: https://traceit-07-i.comp.nus.edu.sg:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
              kv/tracer_backend secret_key | DJANGO_SECRET_KEY;
              database/creds/root username | POSTGRES_USER;
              database/creds/root password | POSTGRES_PASSWORD;
          exportEnv: false

      - name: Get research_backend secrets from Vault
        uses: hashicorp/vault-action@v2.4.0
        id: research_backend-secrets
        with:
          url: https://traceit-07-i.comp.nus.edu.sg:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
              kv/research_backend secret_key | DJANGO_SECRET_KEY;
              database/creds/root username | POSTGRES_USER;
              database/creds/root password | POSTGRES_PASSWORD;
          exportEnv: false

      - name: Deploy tracer_backend
        uses: dawidd6/action-ansible-playbook@v2
        env:
          APP_HOSTS: traceit-01-i.comp.nus.edu.sg
          PAT: ${{ secrets.PAT }}
          REPOSITORY: "IFS4205-TraceIT/tracer-backend"
          APP_NAME: tracer_backend
          DJANGO_SECRET_KEY: "${{ steps.tracer_backend-secrets.outputs.DJANGO_SECRET_KEY }}"
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          POSTGRES_HOST: traceit-01-i.comp.nus.edu.sg
          POSTGRES_DB: postgres
          POSTGRES_USER: "${{ steps.tracer_backend-secrets.outputs.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ steps.tracer_backend-secrets.outputs.POSTGRES_PASSWORD }}"
        with:
          playbook: playbooks/deploy_django.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml

      - name: Deploy research_backend
        uses: dawidd6/action-ansible-playbook@v2
        env:
          APP_HOSTS: traceit-02-i.comp.nus.edu.sg
          PAT: ${{ secrets.PAT }}
          REPOSITORY: "IFS4205-TraceIT/research-backend"
          APP_NAME: research_backend
          DJANGO_SECRET_KEY: "${{ steps.research_backend-secrets.outputs.DJANGO_SECRET_KEY }}"
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          POSTGRES_HOST: traceit-01-i.comp.nus.edu.sg
          POSTGRES_DB: postgres
          # POSTGRES_USER: "${{ steps.research_backend-secrets.outputs.POSTGRES_USER }}"
          # POSTGRES_PASSWORD: "${{ steps.research_backend-secrets.outputs.POSTGRES_PASSWORD }}"
          
          # Temporarily share credentials with tracer_backend
          POSTGRES_USER: "${{ steps.tracer_backend-secrets.outputs.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ steps.tracer_backend-secrets.outputs.POSTGRES_PASSWORD }}"
        with:
          playbook: playbooks/deploy_django.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml

      - name: Download tracer_frontend release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: IFS4205-TraceIT/tracer-frontend
          version: tags/vlatest
          file: tracer-frontend.tar.gz 
          token: ${{ secrets.PAT }}
          target: playbooks/files/tracer-frontend.tar.gz

      - name: Download research_frontend release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: IFS4205-TraceIT/research-frontend
          version: tags/vlatest
          file: research-frontend.tar.gz 
          token: ${{ secrets.PAT }}
          target: playbooks/files/research-frontend.tar.gz
      
      - name: Deploy NGINX
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/deploy_nginx.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml