name: Redeploy service
on:
  schedule:
    # Set to run every 30th minute
    - cron: '*/30 * * * *' 

  workflow_dispatch:
    # inputs:
    #   service_name:
    #     type: choice
    #     description: Which service would you like to redeploy?
    #     required: true
    #     options: 
    #     - tracer
    #     - research
    #     - contact
    #     - proxy
    #     - all

jobs:
  redeploy:

    concurrency: dev
    runs-on: cd-test
    container: 
      image: willhallonline/ansible:2.12-ubuntu-20.04
      options: --dns 192.168.1.101 --dns 8.8.8.8
      volumes:
        - /usr/local/share/ca-certificates/traceit-ca.crt:/traceit-ca.crt
        - /home/cicd/server.crt:/server.crt
        - /home/cicd/server.key:/server.key

    steps:

      - name: Cleanup folder
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Clone repository
        uses: actions/checkout@v3        
      
      - name: Install curl
        run: |
          apt-get update
          apt-get install -y curl
      
      - name: Check if reverse proxy is down
        if: inputs.service_name == '' # If scheduled
        id: proxy-status
        run: |
          STATUSCODE=$(curl --silent --output /dev/stderr --max-time 10 --write-out "%{http_code}"  http://traceit-04-i.comp.nus.edu.sg/)
          echo "STATUSCODE=$STATUSCODE" >> $GITHUB_OUTPUT

      - name: Teardown reverse proxy if it is down, proxy is selected or all are selected
        if: steps.proxy-status.outputs.STATUSCODE == '000'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/teardown_nginx.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_prod.yml

      - name: Deploy proxy
        if: steps.proxy-status.outputs.STATUSCODE == '000'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/deploy_nginx.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_prod.yml
