name: SSH Tunnel
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ci
    container: 
      image: lscr.io/linuxserver/openssh-server:latest
      options: --dns 137.132.90.2 --dns 137.132.85.2 --dns 8.8.8.8
      volumes:
        - /usr/local/share/ca-certificates/traceit-ca.crt:/traceit-ca.crt
        - /home/cicd/server.crt:/server.crt
        - /home/cicd/server.key:/server.key

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      shell: bash

    - name: Install curl
      shell: bash
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y curl unzip openssh-server
        
    - name: Setup tunnel
      shell: bash
      uses: joshlarsen/ssh-tunnel-action@main
      with:
        timeout: 1h
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        ngrok_token: ${{ secrets.NGROK_TOKEN }}