name: Teardown
on:
  workflow_dispatch:

jobs:
  
  teardown:

    runs-on: cd-test
    container: 
      image: ubuntu:20.04
      options: --dns 192.168.1.101

    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      
      - name: Install ansible and dependencies
        run: |
          apt-get update
          apt-get install -y software-properties-common
          apt-add-repository -y ppa:ansible/ansible
          apt-get update
          apt-get install -y sshpass ansible ansible-lint

      - name: Check installation
        run: |
          ansible --version

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Teardown tracer-backend
        uses: dawidd6/action-ansible-playbook@v2
        env:
          APP_HOSTS: traceit-01-i
        with:
          playbook: playbooks/teardown_django.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml

      - name: Teardown Database 1
        uses: dawidd6/action-ansible-playbook@v2
        env:
          DB_HOSTS: traceit-01-i
        with:
          playbook: playbooks/teardown_postgres.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory hosts_dev.yml